using System.Collections.Generic;

using LDOCE5ViewerX.Models;

namespace LDOCE5ViewerX.Services;

/// <summary>
/// Provides the LDOCE advanced-search filter tree.
/// </summary>
public static class AdvancedSearchFilterCatalog
{
    /// <summary>
    /// Gets the top-level advanced-search filters.
    /// </summary>
    public static IReadOnlyList<AdvancedSearchFilterNode> Load()
    {
        return
        [
            new("Most frequent spoken words", null,
            [
                new("1000", "233"),
                new("2000", "234"),
                new("3000", "235"),
            ]),
            new("Most frequent written words", null,
            [
                new("1000", "236"),
                new("2000", "237"),
                new("3000", "238"),
            ]),
            new("Multimedia", null,
            [
                new("Picture", "332"),
                new("Sound effect", "333"),
            ]),
            new("Part of speech", null,
            [
                new("adjective", "334"),
                new("adverb", "335"),
                new("auxiliary verb", "336"),
                new("conjunction", "337"),
                new("determiner", "338"),
                new("interjection", "339"),
                new("modal verb", "340"),
                new("noun", "341",
                [
                    new("uncountable", "u1"),
                ]),
                new("number", "342"),
                new("phrasal verb", "343"),
                new("predeterminer", "344"),
                new("prefix", "345"),
                new("preposition", "346"),
                new("pronoun", "347"),
                new("suffix", "348"),
                new("verb", "349"),
            ]),
            new("Register", null,
            [
                new("biblical", "350"),
                new("formal", "351"),
                new("humorous", "352"),
                new("informal", "353"),
                new("law", "354"),
                new("literary", "355"),
                new("medical", "356"),
                new("not polite", "357"),
                new("old use", "358"),
                new("old-fashioned", "359"),
                new("spoken", "360"),
                new("taboo", "361"),
                new("technical", "362"),
                new("trademark", "363"),
                new("written", "364"),
            ]),
            new("Region", null,
            [
                new("British English", "u2"),
                new("American English", "u3"),
            ]),
            new("Academic Word List", "426"),
            new("Subject", null,
            [
                new("ARTS", "18",
                [
                    new("Architecture", "19"),
                    new("Literature", "20"),
                    new("Media", "21",
                    [
                        new("Film", "22"),
                        new("Television & Radio", "23"),
                    ]),
                    new("Performing", "24",
                    [
                        new("Dance", "25"),
                        new("Music", "26"),
                        new("Theatre", "27"),
                    ]),
                    new("Visual", "28",
                    [
                        new("Design", "29"),
                        new("Painting and Drawing", "30"),
                        new("Sculpture", "31"),
                    ]),
                ]),
                new("BUSINESS", "32",
                [
                    new("Basics", "33",
                    [
                        new("Advertising & Marketing", "34"),
                        new("Business Management", "35"),
                        new("Companies", "36"),
                        new("Offices", "37"),
                        new("Trade", "38"),
                    ]),
                    new("Employment", "39",
                    [
                        new("Conditions of Employment", "40"),
                        new("Labour Relations/Unions", "41"),
                        new("Wages", "42"),
                    ]),
                    new("Finance", "43",
                    [
                        new("Banking", "44"),
                        new("Insurance", "45"),
                        new("Loans", "46"),
                        new("Stocks & Shares", "47"),
                    ]),
                    new("Occupations", "48"),
                ]),
                new("COLOURS & SOUNDS", "49",
                [
                    new("Colours", "50"),
                    new("Shapes/Patterns", "51"),
                    new("Odours", "52"),
                    new("Textures/Sounds", "53"),
                    new("Tastes", "54"),
                ]),
                new("DAILY LIFE", "55",
                [
                    new("Clothes & Fashion", "56",
                    [
                        new("Hair & Beauty", "57"),
                        new("Clothes", "58"),
                        new("Jewellery", "59"),
                    ]),
                    new("Food", "60",
                    [
                        new("Cooking", "61"),
                        new("Drink", "62"),
                        new("Food Dish", "63"),
                        new("Nutrition", "64"),
                        new("Tobacco", "65"),
                        new("Utensils", "66"),
                    ]),
                    new("Games", "67",
                    [
                        new("Board Games", "68"),
                        new("Cards", "69"),
                        new("Darts", "70"),
                        new("Gambling", "71"),
                        new("Other Games", "72"),
                    ]),
                    new("Household", "73",
                    [
                        new("Babies", "74"),
                        new("Cleaning", "75"),
                        new("Furniture", "76"),
                        new("House", "77"),
                        new("Pets", "78"),
                        new("Toys", "79"),
                    ]),
                    new("Leisure", "80",
                    [
                        new("Gardening", "81"),
                        new("Sewing & Knitting", "82"),
                        new("Outdoor", "83"),
                        new("Tourism", "84"),
                    ]),
                    new("Nature", "85"),
                    new("Sport", "86",
                    [
                        new("American Football", "87"),
                        new("Baseball", "88"),
                        new("Cricket", "89"),
                        new("Football", "90"),
                        new("Golf", "91"),
                        new("Horses", "92"),
                        new("Other Sports", "93"),
                        new("Swimming", "94"),
                        new("Tennis", "95"),
                    ]),
                ]),
                new("HARD SCIENCE", "96",
                [
                    new("Astronomy", "97"),
                    new("Biology", "98",
                    [
                        new("Animals", "99"),
                        new("Birds", "100"),
                        new("Fish", "101"),
                        new("Human", "102"),
                        new("Insects", "103"),
                        new("Microbes/Genetics/Biochem", "104"),
                        new("Plants", "105"),
                    ]),
                    new("Chemistry", "106",
                    [
                        new("Compounds", "107"),
                        new("Elements", "108"),
                        new("Plastics", "109"),
                    ]),
                    new("Earth Sciences", "110",
                    [
                        new("Geology", "111"),
                        new("Meteorology", "112"),
                        new("Oceanography", "113"),
                    ]),
                    new("Maths", "114",
                    [
                        new("Numbers", "115"),
                        new("Statistics", "116"),
                    ]),
                    new("Physics", "117",
                    [
                        new("Electricity", "118"),
                        new("Optics", "119"),
                    ]),
                ]),
                new("MEDICINE", "120",
                [
                    new("Alternative Medicine", "121"),
                    new("Birth", "122"),
                    new("Drugs/Medicines", "123",
                    [
                        new("Drug Culture", "124"),
                    ]),
                    new("Hospital", "125"),
                    new("Illness & Disability", "126"),
                    new("Nurses, Doctors, etc", "127"),
                    new("Psychology/Psychiatry", "128"),
                    new("Death", "129"),
                ]),
                new("POLITICS", "130",
                [
                    new("Economics", "131",
                    [
                        new("Currencies", "132"),
                        new("Tax", "133"),
                        new("Welfare", "134"),
                    ]),
                    new("Government", "135",
                    [
                        new("Citizenship", "136"),
                        new("Officials", "137"),
                        new("Parliaments", "138"),
                    ]),
                    new("Military", "139",
                    [
                        new("Army", "140"),
                        new("Defence", "141"),
                        new("Navy", "142"),
                        new("Airforce", "143"),
                        new("Weapons", "144"),
                    ]),
                    new("Politics", "145",
                    [
                        new("Groupings", "146"),
                        new("Policies", "147"),
                        new("Voting", "148"),
                    ]),
                ]),
                new("RELIGION & THOUGHT", "149",
                [
                    new("Folklore", "150"),
                    new("Mythology", "151"),
                    new("Occult", "152",
                    [
                        new("Astrology", "153"),
                        new("Magic", "154"),
                    ]),
                    new("Philosophy", "155"),
                    new("Religion", "156",
                    [
                        new("Buddhism", "157"),
                        new("Christianity", "158"),
                        new("Hinduism", "159"),
                        new("Islam", "160"),
                        new("Judaism", "161"),
                    ]),
                ]),
                new("SOCIETY", "162",
                [
                    new("Anthropology", "163",
                    [
                        new("Nationality & Race", "164"),
                    ]),
                    new("Crime & Law", "165",
                    [
                        new("Bombs & Terrorism", "166"),
                        new("Crime", "167"),
                        new("Jail & punishment", "168"),
                        new("Law", "169"),
                        new("Police", "170"),
                    ]),
                    new("Education", "171",
                    [
                        new("College", "172"),
                        new("Pre School", "173"),
                        new("School", "174"),
                        new("Training", "175"),
                    ]),
                    new("Geography", "176",
                    [
                        new("Environment & waste", "177"),
                    ]),
                    new("History", "178"),
                    new("Linguistics", "179",
                    [
                        new("Letters & punctuation", "180"),
                        new("Grammar", "181"),
                        new("Languages", "182"),
                    ]),
                    new("Sociology", "183",
                    [
                        new("Children", "184"),
                        new("Family", "185"),
                        new("Organizations", "186"),
                        new("Race Relations", "187"),
                        new("Women", "188"),
                        new("Youth", "189"),
                    ]),
                    new("Archaeology", "190"),
                ]),
                new("TECHNOLOGY", "191",
                [
                    new("Agriculture", "192",
                    [
                        new("Crops", "193"),
                        new("Forestry", "194"),
                        new("Soil", "195"),
                    ]),
                    new("Building", "196",
                    [
                        new("Buildings", "197"),
                        new("Construction", "198"),
                    ]),
                    new("Communications", "199",
                    [
                        new("Broadcasting", "200"),
                        new("Mail", "201"),
                        new("Newspapers/Printing/Publishing", "202"),
                        new("Photography", "203"),
                        new("Recording", "204"),
                        new("Telephone/Telegraph", "205"),
                    ]),
                    new("Computers", "206"),
                    new("Engineering", "207",
                    [
                        new("Civil", "208"),
                        new("Electrical", "209"),
                        new("Mechanical", "210"),
                    ]),
                    new("Industry", "211",
                    [
                        new("Crafts", "212"),
                        new("Factories", "213"),
                        new("Glass", "214"),
                        new("Material & Textiles", "215"),
                        new("Pottery & Ceramics", "216"),
                    ]),
                    new("Measurement", "217",
                    [
                        new("Chronology", "218"),
                        new("Temperature", "219"),
                    ]),
                    new("Power", "220",
                    [
                        new("Electricity", "221"),
                        new("Gas/Coal/Oil", "222"),
                        new("Wind/Water/Sun", "223"),
                    ]),
                    new("Transport", "224",
                    [
                        new("Air", "225"),
                        new("Bicycles/Carts/Horses", "226"),
                        new("Motor Vehicles", "227"),
                        new("Roads", "228"),
                        new("Space", "229"),
                        new("Trains & Railways", "230"),
                        new("Water", "231"),
                    ]),
                    new("Tools", "232"),
                ]),
            ]),
            new("Culture", null,
            [
                new("People", "365",
                [
                    new("architects, designers", "368"),
                    new("artists", "369"),
                    new("business", "370"),
                    new("cinema, TV", "371"),
                    new("crime", "372"),
                    new("dancers", "373"),
                    new("economy, finance", "374"),
                    new("educators", "375"),
                    new("engineers, inventors", "376"),
                    new("explorers, navigators", "377"),
                    new("fashion", "378"),
                    new("heroes", "379"),
                    new("lawyers, judges", "380"),
                    new("writers", "381"),
                    new("medical", "382"),
                    new("military", "383"),
                    new("music", "384"),
                    new("philosophers", "385"),
                    new("political", "386"),
                    new("religious", "387"),
                    new("royal", "388"),
                    new("scientists", "389"),
                    new("social reformers", "390"),
                    new("sports", "391"),
                ]),
                new("Places", "366",
                [
                    new("city", "392"),
                    new("country", "393"),
                    new("feature", "394"),
                    new("region", "395"),
                    new("site", "396"),
                ]),
                new("Other", "367",
                [
                    new("arts, architecture", "397"),
                    new("business,commerce", "398"),
                    new("calendar", "399"),
                    new("ceremonies, traditions", "400"),
                    new("cinema, TV", "401"),
                    new("consumer goods", "402"),
                    new("crime", "403"),
                    new("dance companies", "404"),
                    new("economy, finance", "405"),
                    new("education", "406"),
                    new("environmental", "407"),
                    new("fiction", "408"),
                    new("geographical", "409"),
                    new("history", "410"),
                    new("law", "411"),
                    new("literature", "412"),
                    new("medical", "413"),
                    new("military", "414"),
                    new("musical", "415"),
                    new("mythological names", "416"),
                    new("politics", "418"),
                    new("religious", "419"),
                    new("science", "420"),
                    new("social", "421"),
                    new("sports", "422"),
                    new("theatre", "423"),
                    new("transport", "424"),
                ]),
            ]),
            new("Date", null,
            [
                new("8th century", "5"),
                new("9th century", "6"),
                new("10th century", "7"),
                new("11th century", "8"),
                new("12th century", "9"),
                new("13th century", "10"),
                new("14th century", "11"),
                new("15th century", "12"),
                new("16th century", "13"),
                new("17th century", "14"),
                new("18th century", "15"),
                new("19th century", "16"),
                new("20th century", "17"),
            ]),
            new("Language of origin", null,
            [
                new("Afrikaans", "239"),
                new("Aleut", "240"),
                new("Algonquian", "241"),
                new("American Spanish", "242"),
                new("Anglo-French", "243"),
                new("Arabic", "244"),
                new("Aramaic", "245"),
                new("Arawakan", "246"),
                new("Australian Aboriginal", "247"),
                new("Aymara", "248"),
                new("Bantu", "249"),
                new("Canadian French", "250"),
                new("Carib", "251"),
                new("Catalan", "252"),
                new("Celtic", "253"),
                new("Chinese", "254"),
                new("Czech", "255"),
                new("Danish", "256"),
                new("Dharuk", "257"),
                new("Dutch", "258"),
                new("Egyptian", "259"),
                new("English", "260"),
                new("English dialect", "261"),
                new("Flemish", "262"),
                new("French", "263"),
                new("French dialect", "264"),
                new("German", "265"),
                new("German dialect", "266"),
                new("Germanic", "267"),
                new("Greek", "268"),
                new("Hawaiian", "269"),
                new("Hebrew", "270"),
                new("Hindi", "271"),
                new("Hungarian", "272"),
                new("Icelandic", "273"),
                new("Irish Gaelic", "274"),
                new("Italian", "275"),
                new("Italian dialect", "276"),
                new("Japanese", "277"),
                new("Korean", "278"),
                new("Late Greek", "279"),
                new("Late Latin", "280"),
                new("Latin", "281"),
                new("Louisiana French", "282"),
                new("Low German", "283"),
                new("Malay", "284"),
                new("Maori", "285"),
                new("Medieval Greek", "286"),
                new("Medieval Latin", "287"),
                new("Mexican Spanish", "288"),
                new("Middle Dutch", "289"),
                new("Middle High German", "290"),
                new("Middle Low German", "291"),
                new("Modern Greek", "292"),
                new("Modern Latin", "293"),
                new("Nahuatl", "294"),
                new("Narragansett", "295"),
                new("Norwegian", "296"),
                new("Ojibwa", "297"),
                new("Old English", "298"),
                new("Old French", "299"),
                new("Old Irish", "300"),
                new("Old Italian", "301"),
                new("Old Norse", "302"),
                new("Old North French", "303"),
                new("Old Provençal", "304"),
                new("Old Spanish", "305"),
                new("Persian", "306"),
                new("Pidgin English", "307"),
                new("Polish", "308"),
                new("Portuguese", "309"),
                new("Provençal", "310"),
                new("Quechua", "311"),
                new("Romany", "312"),
                new("Russian", "313"),
                new("Sanskrit", "314"),
                new("Scandinavian", "315"),
                new("Scottish English", "316"),
                new("Scottish Gaelic", "317"),
                new("Spanish", "318"),
                new("Swedish", "319"),
                new("Taino", "320"),
                new("Tamil", "321"),
                new("Tibetan", "322"),
                new("Tupi", "323"),
                new("Turkish", "324"),
                new("Urdu", "325"),
                new("Virginia Algonquian", "326"),
                new("Vulgar Latin", "327"),
                new("Welsh", "328"),
                new("West African", "329"),
                new("Yiddish", "330"),
                new("Zulu", "331"),
            ]),
        ];
    }
}
